[package]
name = "ssh-agent-switcher"
version = "0.1.0"
edition = "2024"
publish = false  # Not ready for release yet.

[dependencies]
daemonize = "0.5"
env_logger = "0.11"
libc = "0.2"
log = "0.4"
xdg = "3.0"

[dependencies.getoptsargs]
git = "https://github.com/jmmv/getoptsargs"
rev = "99c61f2f452df1c4fd1894359ac6195162cabb3e"

[dependencies.tokio]
version = "1"
features = ["macros", "net", "rt-multi-thread", "signal"]
